"""Alembic environment.

The database URL comes from `gbmo.config` rather than `alembic.ini`, so there is one
source of truth and no credentials sit in a committed file.

`target_metadata` is deliberately None: migrations here are hand-written SQL, not
autogenerated from ORM models. The schema design is considered work in this project
rather than a by-product of Python classes, and autogenerate would invert that.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from gbmo.config import DATABASE_URL

config = context.config

# Escaped because ConfigParser treats a bare % as interpolation syntax
config.set_main_option("sqlalchemy.url", DATABASE_URL.replace("%", "%%"))

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting. Useful for reviewing a migration."""
    context.configure(
        url=DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
