"""bidding zone panel

The cross-country layer. Hourly day-ahead price, load and aggregated generation for a
curated set of European bidding zones, sourced from the ENTSO-E Transparency Platform.

## Why this is a parallel star and not a `country` column on the GB tables

The handover note proposed adding a country dimension to `settlement_period`, `price`,
`generation` and `demand`. That was the wrong shape, for four reasons that only became
clear on reading the GB schema against what ENTSO-E actually returns:

1. `settlement_period` is a *GB settlement* calendar. Its `period` column counts 1-48 on
   the local clock, 46 or 50 on clock-change days, and that object does not exist outside
   GB. A country column would leave it meaningless on every row but one country's.
2. `generation` references `fuel`, which carries GB SRMC parameters: QEP gas, Carbon
   Price Support, UK ETS. Those are British tax and market instruments. ENTSO-E
   production types have no relationship with that costing layer.
3. The GB ETL truncates with RESTART IDENTITY, which reassigns every `time_id`. Sharing
   those tables would mean each GB reload silently invalidated European rows that are
   slow and rate-limited to re-fetch. Weather already had to be kept out of that blast
   radius for exactly this reason.
4. The grains differ: GB is half-hourly, ENTSO-E hourly.

So the two live side by side in one database, sharing `gbmo.arbitrage` (which takes a
price vector and a battery spec and knows nothing about any country) but not the GB
costing layer, which stays explicitly British.

Revision ID: b91c4a7d2e05
Revises: a305783f9fcc
Create Date: 2026-09-05
"""

from alembic import op

revision = "b91c4a7d2e05"
down_revision = "a305783f9fcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Hand-curated modelling layer, like `fuel` and `weather_location`. Populated from
    # gbmo.ingest.zones rather than inline here, so the rationale for each zone stays
    # next to the code that fetches it.
    #
    # A surrogate SMALLINT key rather than the natural `code`, which is the one place
    # this schema deviates from `weather_location`'s natural text key. The reason is
    # measured, not stylistic: `weather` repeats its text location on every row and costs
    # 157 bytes/row against 76 for `generation`. At 3M panel rows that difference is
    # ~200MB of text that carries no information.
    op.execute("""
        CREATE TABLE zone (
            zone_id      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code         TEXT NOT NULL UNIQUE,   -- ENTSO-E area code, e.g. 'DK_1'
            country_code TEXT NOT NULL,          -- ISO 3166-1 alpha-2, for aggregating up
            name         TEXT NOT NULL,
            timezone     TEXT NOT NULL,          -- IANA name; facts are UTC, this converts back
            currency     TEXT NOT NULL,          -- currency of the day-ahead price
            rationale    TEXT NOT NULL           -- why this zone earns a place in the panel
        )
    """)

    # Day-ahead auction clearing price, one row per zone-hour.
    #
    # No currency column: it is a property of the zone, not of the hour, and belongs in
    # the dimension. Conversion to a common currency is a query-time join against
    # `commodity_price`, where the ECB FX series already lives, for the same reason the
    # EUA series is stored in euros and converted in the query.
    #
    # No CHECK on sign. Negative clearing prices are a real and increasingly common
    # outcome in high-VRE zones, and they are precisely the hours a battery earns in.
    op.execute("""
        CREATE TABLE zone_price (
            zone_id  SMALLINT NOT NULL REFERENCES zone(zone_id),
            datetime TIMESTAMP NOT NULL,  -- UTC, naive, matching the GB tables
            price    DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (zone_id, datetime)
        )
    """)

    op.execute("""
        CREATE TABLE zone_load (
            zone_id  SMALLINT NOT NULL REFERENCES zone(zone_id),
            datetime TIMESTAMP NOT NULL,
            mw       DOUBLE PRECISION NOT NULL CHECK (mw >= 0),
            PRIMARY KEY (zone_id, datetime)
        )
    """)

    # Generation, wide and pre-aggregated. This is a deliberate exception to the
    # store-as-observed convention and the reasoning is in docs/conventions.md; the short
    # version is that the full per-production-type response is cached on disk, so
    # regrouping these categories is a reload rather than a re-fetch. The convention
    # exists to keep combination rules revisable, and the cache preserves that property
    # here without paying 1.3GB for the long form.
    #
    # NULL and 0.0 are different answers. NULL means the zone does not report that
    # category at all; 0.0 means it reported zero output. France reporting no offshore
    # wind line before 2022 is not the same fact as France reporting zero offshore wind.
    #
    # No total column: it is the sum of the others, so under the no-derived-data rule it
    # is a query-time computation.
    op.execute("""
        CREATE TABLE zone_generation (
            zone_id    SMALLINT NOT NULL REFERENCES zone(zone_id),
            datetime   TIMESTAMP NOT NULL,
            wind_mw    DOUBLE PRECISION,
            solar_mw   DOUBLE PRECISION,
            hydro_mw   DOUBLE PRECISION,
            nuclear_mw DOUBLE PRECISION,
            fossil_mw  DOUBLE PRECISION,
            storage_mw DOUBLE PRECISION,  -- pumped hydro and batteries: the incumbent arbitrageur
            other_mw   DOUBLE PRECISION,
            PRIMARY KEY (zone_id, datetime)
        )
    """)

    # Panel regressions slice by time across zones ("what happened everywhere on this
    # day"), which the (zone_id, datetime) primary keys cannot serve on their leftmost
    # prefix. One index per fact table, matching the idx_generation_fuel_id precedent.
    for table in ("zone_price", "zone_load", "zone_generation"):
        op.execute(f"CREATE INDEX idx_{table}_datetime ON {table}(datetime)")

    # What was actually fetched, and at what native resolution.
    #
    # This is an observed fact about an ingest, not derived data: from October 2025 some
    # zones publish day-ahead prices on a 15-minute MTU rather than hourly, and the
    # loader resamples them to hourly. Without a record of the source resolution, a
    # future reader cannot tell a genuinely flat hour from four averaged quarters. Cheap
    # to keep at roughly 20 zones x 9 years x 3 datasets.
    op.execute("""
        CREATE TABLE zone_ingest (
            zone_id             SMALLINT NOT NULL REFERENCES zone(zone_id),
            dataset             TEXT NOT NULL,  -- 'price' | 'load' | 'generation'
            year                INTEGER NOT NULL,
            resolution_minutes  INTEGER NOT NULL,
            source_rows         INTEGER NOT NULL,  -- as published, before hourly resampling
            fetched_at          TIMESTAMP NOT NULL,
            PRIMARY KEY (zone_id, dataset, year)
        )
    """)


def downgrade() -> None:
    for table in ("zone_ingest", "zone_generation", "zone_load", "zone_price", "zone"):
        op.execute(f"DROP TABLE IF EXISTS {table}")
