"""baseline schema

Ports the six tables from the SQLite build (schema.sql) to Postgres. Three deliberate
changes, and nothing else:

1. `time` becomes `settlement_period`. `time` is a type name in Postgres and would need
   quoting at every use site. The rename also says what the row actually is: a half-hour
   GB settlement period, not a generic instant.
2. `TEXT` datetimes become real temporal types (`TIMESTAMP`, `DATE`). Sorting ISO strings
   works by luck; date arithmetic does not work at all.
3. `REAL` becomes `DOUBLE PRECISION`. SQLite's REAL is already 8-byte; Postgres REAL is
   4-byte, so a literal port would silently lose precision.

`datetime` is `TIMESTAMP WITHOUT TIME ZONE` on purpose. The source timestamps are naive
local UK times, evidenced by the duplicate rows the loader drops on clock-change days.
Storing them as `TIMESTAMPTZ` would require inventing an offset and resolving the autumn
ambiguity, which is a modelling decision this migration has no business making. The
honest fix later is to derive UTC from settlement date plus settlement period, which is
unambiguous by construction.

`is_dispatchable` stays INTEGER rather than becoming BOOLEAN, deliberately: this
migration is a port, and changing a value representation at the same time would make the
equivalence diff against the SQLite build meaningless. Worth revisiting on its own.

Revision ID: ed7e02dcf29d
Revises:
Create Date: 2026-09-02
"""

from alembic import op

revision = "ed7e02dcf29d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Dimension: one row per fuel type. Hand-curated modelling layer (mc, carbon_factor
    # are assumptions, not observations) kept separate from the observed facts.
    op.execute("""
        CREATE TABLE fuel (
            fuel_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            TEXT NOT NULL UNIQUE,
            mc              DOUBLE PRECISION NOT NULL,  -- static SRMC (v1); still the price where commodity IS NULL
            carbon_factor   DOUBLE PRECISION NOT NULL,  -- kgCO2 per MWh of electricity = heat emissions / efficiency
            efficiency      DOUBLE PRECISION,           -- LHV basis. NULL where there is no fuel cost to model
            commodity       TEXT,                       -- 'gas' | 'coal'. NULL = no series, fall back to mc
            is_dispatchable INTEGER NOT NULL
        )
    """)

    # Dimension: one row per half-hourly settlement period. Calendar attributes are
    # stored (not derived at query time) because a calendar is immutable: no
    # update-anomaly risk.
    op.execute("""
        CREATE TABLE settlement_period (
            time_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            datetime TIMESTAMP NOT NULL UNIQUE,
            date     DATE NOT NULL,
            month    INTEGER NOT NULL,
            year     INTEGER NOT NULL,
            season   TEXT NOT NULL
        )
    """)

    # One row = MW of one fuel at one time period
    op.execute("""
        CREATE TABLE generation (
            time_id INTEGER NOT NULL REFERENCES settlement_period(time_id),
            fuel_id INTEGER NOT NULL REFERENCES fuel(fuel_id),
            mw      DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (time_id, fuel_id)
        )
    """)
    # Composite PK uses leftmost-prefix convention, so fuel-only aggregations need this
    op.execute("CREATE INDEX idx_generation_fuel_id ON generation(fuel_id)")

    # One row = demand at one time
    op.execute("""
        CREATE TABLE demand (
            time_id INTEGER PRIMARY KEY REFERENCES settlement_period(time_id),
            nd      DOUBLE PRECISION NOT NULL,  -- National Demand
            tsd     DOUBLE PRECISION NOT NULL   -- Transmission System Demand; ND would bias the price down
        )
    """)

    # One row = actual price paid at one time. Divergence from the modelled price
    # signals balancing actions.
    op.execute("""
        CREATE TABLE price (
            time_id INTEGER PRIMARY KEY REFERENCES settlement_period(time_id),
            price   DOUBLE PRECISION NOT NULL
        )
    """)

    # Monthly commodity prices so thermal SRMC can be computed at query time instead of
    # using the static fuel.mc. Every series is stored as observed and separately from
    # every other: the EUA->UKA splice, whether CPS is added, and whether gas comes from
    # QEP or SAP are all modelling choices, so they belong in the query, not the data.
    # `source` keeps two series for the same commodity apart, which is what makes that
    # choice a query-time one. Units differ by commodity, hence the unit column: never
    # sum or compare across commodities without reading it.
    op.execute("""
        CREATE TABLE commodity_price (
            year      INTEGER NOT NULL,
            month     INTEGER NOT NULL,
            commodity TEXT NOT NULL,  -- 'gas' | 'coal' | 'carbon' | 'fx' (joins to fuel.commodity)
            source    TEXT NOT NULL,  -- 'qep' | 'sap' | 'eua' | 'uka' | 'cps' | 'ecb'
            price     DOUBLE PRECISION NOT NULL,
            unit      TEXT NOT NULL,  -- 'pence_per_kWh_GCV' | 'GBP_per_tCO2' | 'GBP_per_EUR'
            PRIMARY KEY (year, month, commodity, source)
        )
    """)


def downgrade() -> None:
    # Reverse dependency order: facts before the dimensions they reference
    for table in ("commodity_price", "price", "demand", "generation",
                  "settlement_period", "fuel"):
        op.execute(f"DROP TABLE IF EXISTS {table}")
