"""arbitrage tables

Five tables for the battery arbitrage study: two dimensions describing the asset and
the strategy, a run record, and two facts holding what a run produced.

Model outputs are the second sanctioned exception to the no-derived-data rule, for two
distinct reasons. Learned strategies (LSTM, RL) are not recomputable at all: they depend
on trained weights, a seed and a horizon, none of which the database holds. Deterministic
strategies (perfect-foresight LP, naive heuristic) are perfectly recomputable but not
affordably so, since re-solving an optimisation over ~300k settlement periods is not a
query-time computation in any useful sense. Both are observations *of a run*.

Profit is deliberately absent. It is a join of `dispatch` against `price`, so under the
convention it must be computed rather than stored. Store what a run did; compute what it
earned.

Revision ID: f75c7e384d2f
Revises: ed7e02dcf29d
Create Date: 2026-09-02
"""

from alembic import op

revision = "f75c7e384d2f"
down_revision = "ed7e02dcf29d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Dimension: the asset being simulated. Hand-curated assumptions, so it sits
    # alongside `fuel` as a modelling layer rather than an observed fact.
    #
    # Duration is capacity_mwh / power_mw and is deliberately not stored: it is exactly
    # the kind of derivable value the convention keeps out of the database.
    op.execute("""
        CREATE TABLE battery_spec (
            battery_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name                  TEXT NOT NULL UNIQUE,
            power_mw              DOUBLE PRECISION NOT NULL CHECK (power_mw > 0),
            capacity_mwh          DOUBLE PRECISION NOT NULL CHECK (capacity_mwh > 0),
            -- One-way efficiency is taken as the square root of this, applied to each leg
            round_trip_efficiency DOUBLE PRECISION NOT NULL
                                  CHECK (round_trip_efficiency > 0 AND round_trip_efficiency <= 1),
            min_soc_mwh           DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (min_soc_mwh >= 0),
            -- NULL means unconstrained, which is what the ceiling run wants
            max_cycles_per_day    DOUBLE PRECISION CHECK (max_cycles_per_day > 0),
            CONSTRAINT floor_below_ceiling CHECK (min_soc_mwh < capacity_mwh)
        )
    """)

    # Power held constant across the three specs on purpose. For a price-taker,
    # arbitrage value scales roughly linearly with power, so varying it reveals nothing;
    # holding it fixed isolates duration as the single independent variable. 50 MW keeps
    # the price-taker assumption honest against 20-45 GW of GB demand.
    #
    # The 1-hour row is not a strawman: the first GB grid-scale fleet, built for the 2016
    # Enhanced Frequency Response auction and commissioned across 2017-18, was almost all
    # one hour or under. It is what the market actually built when this price data starts.
    op.execute("""
        INSERT INTO battery_spec (name, power_mw, capacity_mwh, round_trip_efficiency)
        VALUES ('1h_50mw', 50, 50,  0.85),
               ('2h_50mw', 50, 100, 0.85),
               ('4h_50mw', 50, 200, 0.85)
    """)

    op.execute("""
        CREATE TABLE strategy (
            strategy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL
        )
    """)

    op.execute("""
        INSERT INTO strategy (name, description) VALUES
        ('lp_perfect_foresight',
         'Linear program with known future prices. The ceiling: no strategy can beat it.'),
        ('naive_tod',
         'Fixed time-of-day rule, charging overnight and discharging at peak. The floor.'),
        ('lstm_mpc',
         'LSTM price forecast feeding the same LP over a receding horizon.'),
        ('rl_dqn',
         'Reinforcement learning agent choosing dispatch directly from state.')
    """)

    # The reproducibility record. A dispatch schedule means nothing without the code,
    # configuration and seed that produced it. A NULL seed is a positive statement that
    # the run was deterministic, not a missing value.
    #
    # created_at is TIMESTAMPTZ because it records a real wall-clock event. The period
    # bounds are TIMESTAMP to match settlement_period.datetime, which is naive UTC.
    op.execute("""
        CREATE TABLE model_run (
            run_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            strategy_id   INTEGER NOT NULL REFERENCES strategy(strategy_id),
            battery_id    INTEGER NOT NULL REFERENCES battery_spec(battery_id),
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            git_commit    TEXT NOT NULL,
            config        JSONB NOT NULL,
            seed          INTEGER,
            period_start  TIMESTAMP NOT NULL,
            period_end    TIMESTAMP NOT NULL,
            -- optimal / infeasible / time-limit. An observation of the run, and not
            -- cheaply recomputable: it records whether the LP actually reached optimality.
            solver_status TEXT,
            CONSTRAINT window_ordered CHECK (period_end > period_start)
        )
    """)
    op.execute("CREATE INDEX idx_model_run_strategy_battery ON model_run(strategy_id, battery_id)")

    # Fact: what the strategy did in each settlement period.
    #
    # Charge and discharge are separate columns rather than one signed value. The reason
    # is error detection, not storage. Simultaneous charge and discharge is a real LP
    # failure mode, appearing when efficiency is mis-specified and during negative price
    # periods where the optimiser finds it profitable to burn energy by cycling it in and
    # out at once. A signed column cannot represent that state, so the bug would be
    # silently netted away; separate columns plus the constraint below catch it.
    op.execute("""
        CREATE TABLE dispatch (
            run_id       INTEGER NOT NULL REFERENCES model_run(run_id) ON DELETE CASCADE,
            time_id      INTEGER NOT NULL REFERENCES settlement_period(time_id),
            charge_mw    DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (charge_mw >= 0),
            discharge_mw DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (discharge_mw >= 0),
            soc_mwh      DOUBLE PRECISION NOT NULL CHECK (soc_mwh >= 0),
            PRIMARY KEY (run_id, time_id),
            CONSTRAINT not_both_directions CHECK (charge_mw = 0 OR discharge_mw = 0)
        )
    """)
    # Comparing strategies at the same period is the core query, so time_id needs its own
    # index: the composite PK is leftmost-prefixed on run_id.
    op.execute("CREATE INDEX idx_dispatch_time_id ON dispatch(time_id)")

    # Fact: predicted prices, one row per (run, forecast origin, horizon step).
    #
    # A receding-horizon controller makes a fresh forecast at every step, so a prediction
    # carries two timestamps: when it was made and which period it is about. Collapsing
    # them would lose the ability to ask how forecast error grows with horizon, which is
    # the main thing worth knowing about a forecaster.
    op.execute("""
        CREATE TABLE forecast (
            run_id          INTEGER NOT NULL REFERENCES model_run(run_id) ON DELETE CASCADE,
            origin_time_id  INTEGER NOT NULL REFERENCES settlement_period(time_id),
            horizon_step    SMALLINT NOT NULL CHECK (horizon_step > 0),
            target_time_id  INTEGER NOT NULL REFERENCES settlement_period(time_id),
            predicted_price DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (run_id, origin_time_id, horizon_step)
        )
    """)
    op.execute("CREATE INDEX idx_forecast_target ON forecast(target_time_id)")


def downgrade() -> None:
    for table in ("forecast", "dispatch", "model_run", "strategy", "battery_spec"):
        op.execute(f"DROP TABLE IF EXISTS {table}")
