"""Assemble and compile the paper.

Tables are never typed into the prose. A section writes `{{table:t2_main|Caption}}` and
this script splices in paper/tables/t2_main.md, generated by gbmo.analysis.results, with
its caption and notes. Numbers quoted in the text come from paper/results.json. So a rerun
of the analysis can change what the paper says, but it cannot leave the paper saying
something the analysis no longer shows.

    python paper/build.py            # -> paper/build/paper.pdf
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUILD = HERE / "build"
INCLUDE = re.compile(r"^\{\{table:(?P<name>[\w]+)\|(?P<caption>.+)\}\}\s*$")


def uncount_bare_tables(text):
    """Stop uncaptioned tables from consuming a table number.

    LaTeX's longtable steps the table counter even when a table has no caption, so every
    small inline table (the operator ladder, the zone types) silently renumbered every
    captioned table after it, and "Table 1" in the text pointed at what printed as Table 3.
    """
    lines = text.splitlines()
    out = []
    for i, line in enumerate(lines):
        out.append(line)
        is_last_row = line.startswith("|") and (i + 1 == len(lines) or not lines[i + 1].startswith("|"))
        if is_last_row:
            block_start = i
            while block_start > 0 and lines[block_start - 1].startswith("|"):
                block_start -= 1
            before = lines[block_start - 2] if block_start >= 2 else ""
            after = lines[i + 2] if i + 2 < len(lines) else ""
            if not (before.startswith("Table:") or after.startswith("Table:")):
                out += ["", "\\addtocounter{table}{-1}"]
    return "\n".join(out)


def splice(text):
    out = []
    for line in text.splitlines():
        m = INCLUDE.match(line)
        if not m:
            out.append(line)
            continue
        body = (HERE / "tables" / f"{m['name']}.md").read_text(encoding="utf-8").strip()
        table, _, notes = body.partition("\n\n")
        out += ["", f"Table: {m['caption']}", "", table, "",
                # Size switches, not an environment: pandoc passes a whole begin/end block
                # through as raw LaTeX, leaving the notes' underscores unescaped
                "\\footnotesize", "", f"*Notes:* {notes.strip()}", "", "\\normalsize", ""]
    return "\n".join(out)


def main():
    BUILD.mkdir(exist_ok=True)
    sections = sorted((HERE / "sections").glob("*.md"))
    combined = "\n\n".join(uncount_bare_tables(splice(p.read_text(encoding="utf-8")))
                           for p in sections)
    source = BUILD / "paper.md"
    source.write_text(combined, encoding="utf-8")
    cmd = ["pandoc", str(HERE / "metadata.yaml"), str(source), "--citeproc",
           "--pdf-engine=xelatex", f"--resource-path={HERE}", "-o", str(BUILD / "paper.pdf"),
           *sys.argv[1:]]
    subprocess.run(cmd, check=True, cwd=HERE)
    print(f"built {BUILD / 'paper.pdf'}")


if __name__ == "__main__":
    main()
